dev-6.1: функция-архиватор
SHTYKOVYCH/OS-labs pull request #15
Opened 2022-03-09 16:17 UTC by lonelyfox-dev

- НЕ ФИНАЛЬНАЯ ВЕРСИЯ. Вроде как работает, но возможно, нужны подкрутки, подстройка возвращаемых значений и т.д. Чтоб ничего лишнего не пердело и не свистело

- Комментов не много, соответственно. Пример работы для наглядности в директории lab1_misc

- Внутри lab1_misc: text.txt - архив, tree.txt - дерево архивируемой директории. При надобности, могу отправить саму директорию на репку

2022-03-09 16:19 UTC, lonelyfox-dev commented on lab1_misc/tree.txt
> +└── tree.txt
На этот файл не смотрим, забыл его вырезать

2022-03-09 16:19 UTC, lonelyfox-dev commented on lab1_misc/tree.txt
> +└── tree.txt
(Который tree.txt)

2022-03-09 16:29 UTC, SHTYKOVYCH commented on lab1_misc/tree.txt
> +└── tree.txt
Так бахни git rm --cashed <filename>

2022-03-09 18:45 UTC, SHTYKOVYCH requested changes
Я пожалуй подожду финальной версии, пока я в слишком глубоком ахуе
Структура файла в первых байтах точно неверная, так что надо менять. 
В общем, жду финальной версии

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +        if (entry->d_type == 4)
без комментиков тяжко конечно

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +            if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0 )
О нет, единство код стайла сравнения строк...

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +    char *buff = malloc(sizeof(char) * 65536);
может это в стаке бахнуть?

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +void archive(char *dir)	// Требуется указывать полный путь до архивируемой папки. К примеру, /home/nikolay/Testdir
Относительные не работают?

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +    sprintDir(dir, buff, &count);
а нахера, я ж писал, что храним число записей в архиве как unsigned int. похер, что int будет, главное что сыро храним

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +    writeFile(filedescr, buff, strlen(buff));
тут, соответственно, будет просто write(filedescr, &count, 4)

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +void archive(char *dir)	// Требуется указывать полный путь до архивируемой папки. К примеру, /home/nikolay/Testdir
И надо ли передавать в саму прогу абсолютный путь

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +    writeFile(filedescr, count_str, strlen(count_str));
тут вообще 12 байт запишется, а sizeof int вроде 4 считается

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +        perror(dir);
потом попробую над этим побольше подумать, может переведу все на такой механизм. Но это я без тебя просто вылизывать все буду

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +            sprintf(buff, "{name:\"%s\",parentDir:\"%s\",type=\"d\"}", entry->d_name, dir);
Я для этого написал jsonStringify

2022-03-09 18:45 UTC, SHTYKOVYCH commented on lab1/archive.c
> +            readFile(filedescr, contents, statbuf.st_size);
нахера читали чтение из файла, непонятно...
Бугурчу шо пиздец, понимаю, что не финал, но бугурчу

2022-03-14 14:31 UTC, lonelyfox-dev commented on lab1/archive.c
> +    lseek(filedescr, 0L, SEEK_SET);
Если прям очень хочется пользоваться по максимуму написанными вспомогательными функциями, могу дописать функцию перевода указателя, чтоб можно было передавать третий аргумент

2022-03-14 20:20 UTC, SHTYKOVYCH commented on lab1/archive.c
> +            sprintDir(filedescr, entry->d_name, str, jason, count); // Ре курсия
Т е ты сначала пишешь всю инфу о дочерних для текущей директории вхождений, а только потом о самой директории?

2022-03-16 20:28 UTC, merged